---
title: "Content-Based Filtering Model"
author: "Xi Sun"
date: "April 8, 2019"
output: pdf_document
---

## Libraries

```{r,warning=FALSE,message=FALSE}
library(hopach)
```

## Loading the dataset

```{r}
business <- read.csv("C:/Users/31586/Desktop/yelp_dataset/businessV2.csv",header=TRUE)
#nrow(business) #24638
#ncol(business) #91
#head(business,100)
```

## Algorithm

```{r,message=FALSE}
catlist <- function(...){
  x_vec <- trimws(tolower(as.character(c(...))))
  typename_vec <- tolower(names(business)[12:90])
  n <- length(x)
  ind1 <- which(typename_vec %in% x_vec)
  if (n==0){
    return("Please select something!")
  }else{
    if (sum(is.na(ind1)!=0)){
      return("Please select from the list")
    }else{
      x_vec <- x_vec
    }
  }
  ind <- business[,1]
  mat1 <- business[,12:90]
  mat2 <- mat1[,ind1]
  vec_0 <- rep(0,nrow(business))
  for (i in 1:n){
    vec_0 <- vec_0+mat2[,i]
  }
  mat3 <- cbind(ind,vec_0)
  ind_0 <- which(mat3[,2]==0)
  mat3 <- mat3[-ind_0,]
  list1 <- mat3[,1]
  datalist <- business[list1,c(1,3,10)]
  data_order <- datalist[order(datalist$stars,decreasing=TRUE),]
  return(head(data_order,5))
} #Generate list based on category

randsample <- function(){
  rand_ind <- sample(1:nrow(business))
  rand <- business[rand_ind,c(3:7,10)]
  return(head(rand,5))
} #Generate list at random

sele <- readline(prompt="Please select from above: ") #This is for user input
```

## Content Based Filtering

```{r,message=FALSE}
cbf <- function(...,numberOfResult=5){
  x_ind <- c(...)
  if (all(x_ind %in% rownames(randsample()))){
    x_ind <- x_ind
  }else{
    return("Please select from the list!")
  }
  n <- length(x_ind)
  m <- nrow(business)
  if (n==0){
    return("Please select something!")
  }else{
    x_ind <- x_ind
  }
  mat1 <- business[x_ind,12:90]
  x_0 <- rep(0,nrow(business))
  for (i in 1:n){
    x_0 <- x_0+mat1[i,]
  }
  x_vec <- x_0/sum(x_0)
  tx_vec <- t(x_vec)
  bus_mat <- business[,12:90]/business[,91]
  dist_mat <- 1-distancevector(bus_mat,tx_vec,"cosangle")
  result_mat <- cbind(business[,c(3:7,10)],dist_mat)
  result_order <- result_mat[order(result_mat$dist_mat,decreasing=TRUE),]
  result <- head(result_order,numberOfResult)[,-7]
  rownames(result) <- c()
  return(result)
}
cbf(1,2,numberOfResult=10)
```



